# Generated by Django 3.2.7 on 2021-10-04 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0017_auto_20211004_0743'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Oligo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('sequence', models.CharField(max_length=150)),
                ('scale', models.CharField(max_length=20)),
                ('purity', models.CharField(max_length=20)),
                ('modification', models.CharField(max_length=150)),
                ('quantity', models.IntegerField()),
                ('name', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivery_date', models.DateField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('volume', models.IntegerField()),
                ('OD_reading', models.DecimalField(decimal_places=2, max_digits=5)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oligo_orders', to='accounts.account')),
                ('submitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oligo_orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
