# Generated by Django 3.2.7 on 2021-10-04 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oligos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oligo',
            name='modification',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
