# Generated by Django 3.2.7 on 2021-10-04 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oligos', '0002_alter_oligo_modification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oligo',
            name='OD_reading',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5),
        ),
    ]
