# Generated by Django 3.2.7 on 2021-10-04 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oligos', '0003_alter_oligo_od_reading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oligo',
            name='delivery_date',
            field=models.DateField(null=True),
        ),
    ]
