# Generated by Django 3.2.7 on 2021-10-04 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oligos', '0004_alter_oligo_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oligo',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
