# Generated by Django 3.2.7 on 2021-10-04 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oligos', '0005_alter_oligo_delivery_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oligo',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='oligo',
            name='OD_reading',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
