# Generated by Django 3.2.7 on 2021-10-06 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oligos', '0006_auto_20211004_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oligo',
            name='quantity',
        ),
    ]
