# Generated by Django 3.2.7 on 2021-10-06 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oligos', '0007_remove_oligo_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oligo',
            name='modification',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='oligo',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='oligo',
            name='volume',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
