# Generated by Django 3.2.8 on 2021-10-27 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oligos', '0009_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
