# Generated by Django 3.2.8 on 2021-10-27 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oligos', '0010_price_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oligo',
            name='volume',
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=6, null=True),
        ),
    ]
