# Generated by Django 3.2.8 on 2021-10-28 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oligos', '0011_alter_oligo_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='oligo',
            name='OD_reading_dilution_factor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
