# Generated by Django 3.2.8 on 2021-11-01 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oligos', '0012_oligo_od_reading_dilution_factor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Price',
            new_name='OliPrice',
        ),
    ]
