# Generated by Django 3.2.8 on 2021-11-04 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oligos', '0013_rename_price_oliprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oligo',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Oligo Name'),
        ),
        migrations.AlterField(
            model_name='oligo',
            name='sequence',
            field=models.CharField(max_length=150, verbose_name='Sequence 5′ to 3′'),
        ),
    ]
