# Generated by Django 3.2.8 on 2021-11-17 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oligos', '0014_auto_20211104_1221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oligo',
            name='price',
        ),
    ]
