# Generated by Django 3.2.8 on 2021-10-08 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0017_auto_20211004_0743'),
    ]

    operations = [
        migrations.CreateModel(
            name='Primer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('concentration', models.IntegerField()),
                ('volume', models.IntegerField()),
                ('melting_temperature', models.IntegerField()),
                ('common', models.BooleanField()),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_id', models.IntegerField()),
                ('template_name', models.CharField(max_length=150)),
                ('plate_name', models.CharField(blank=True, max_length=20, null=True)),
                ('well', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('s', 'Submitted'), ('p', 'Preparing'), ('r', 'Running'), ('c', 'Completed')], max_length=1)),
                ('submit_date', models.DateTimeField(auto_now_add=True)),
                ('completed_date', models.DateTimeField()),
                ('template_comment', models.CharField(choices=[('no', 'None'), ('gc', 'GC rich'), ('at', 'AT rich'), ('lr', 'Long repeat'), ('hp', 'Homopolymer')], max_length=2)),
                ('template_type', models.CharField(choices=[('pl', 'Plasmid'), ('pp', 'PCR product'), ('co', 'Cosmid'), ('ot', 'Other')], max_length=2)),
                ('template_size', models.IntegerField()),
                ('insert_size', models.IntegerField()),
                ('pcr_purify', models.BooleanField()),
                ('template_concentration', models.IntegerField()),
                ('template_volume', models.IntegerField()),
                ('hardcopy', models.BooleanField()),
                ('filename', models.CharField(max_length=150)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
                ('primer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sequences.primer')),
                ('submitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
