# Generated by Django 3.2.8 on 2021-10-08 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sequences', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sequence',
            old_name='submit_date',
            new_name='create_date',
        ),
    ]
