# Generated by Django 3.2.8 on 2021-10-08 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sequences', '0002_rename_submit_date_sequence_create_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='primer',
            name='sequence',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='primer',
            name='common',
            field=models.BooleanField(verbose_name='Is an LSD common primer'),
        ),
        migrations.AlterField(
            model_name='sequence',
            name='primer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequences', to='sequences.primer'),
        ),
    ]
