# Generated by Django 3.2.8 on 2021-10-08 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequences', '0003_auto_20211008_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primer',
            name='melting_temperature',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
