# Generated by Django 3.2.8 on 2021-10-08 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequences', '0004_alter_primer_melting_temperature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequence',
            name='completed_date',
            field=models.DateField(),
        ),
    ]
