# Generated by Django 3.2.8 on 2021-10-08 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequences', '0005_alter_sequence_completed_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequence',
            name='pcr_purify',
            field=models.BooleanField(verbose_name='PCR Purify?'),
        ),
        migrations.AlterField(
            model_name='sequence',
            name='well',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
