# Generated by Django 3.2.8 on 2021-10-08 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequences', '0006_auto_20211008_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primer',
            name='common',
            field=models.BooleanField(blank=True, null=True, verbose_name='Is an LSD common primer'),
        ),
        migrations.AlterField(
            model_name='primer',
            name='concentration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='primer',
            name='volume',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
