# Generated by Django 3.2.8 on 2021-10-08 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequences', '0007_auto_20211008_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequence',
            name='filename',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
