# Generated by Django 3.2.8 on 2021-10-08 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequences', '0008_alter_sequence_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequence',
            name='completed_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
