# Generated by Django 3.2.8 on 2021-10-08 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequences', '0009_alter_sequence_completed_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequence',
            name='insert_size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
