# Generated by Django 3.2.8 on 2021-10-08 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequences', '0010_alter_sequence_insert_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequence',
            name='hardcopy',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
