# Generated by Django 3.2.8 on 2021-10-12 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sequences', '0012_auto_20211012_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='reaction',
            name='submitter',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='accounts.user'),
            preserve_default=False,
        ),
    ]
