# Generated by Django 3.2.8 on 2021-10-12 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequences', '0013_reaction_submitter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaction',
            name='hardcopy',
            field=models.BooleanField(default=False),
        ),
    ]
