# Generated by Django 3.2.8 on 2021-10-13 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequences', '0014_alter_reaction_hardcopy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='comment',
            field=models.CharField(blank=True, choices=[('no', 'None'), ('gc', 'GC rich'), ('at', 'AT rich'), ('lr', 'Long repeat'), ('hp', 'Homopolymer')], default='no', max_length=2, null=True),
        ),
    ]
