# Generated by Django 3.2.8 on 2021-10-13 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequences', '0015_alter_template_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primer',
            name='concentration',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='primer',
            name='volume',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
