# Generated by Django 3.2.8 on 2021-10-13 13:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sequences', '0016_auto_20211013_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='primer',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
