# Generated by Django 3.2.8 on 2021-10-15 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequences', '0017_primer_create_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reaction',
            name='sequence_id',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
