# Generated by Django 3.2.8 on 2021-10-15 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sequences', '0018_reaction_sequence_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reaction',
            name='sequence_id',
        ),
    ]
