# Generated by Django 3.2.8 on 2021-10-15 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequences', '0019_remove_reaction_sequence_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='reaction',
            name='sequence_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
