# Generated by Django 3.2.8 on 2021-10-20 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequences', '0020_reaction_sequence_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='reaction',
            name='comment',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
