# Generated by Django 3.2.8 on 2021-11-01 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequences', '0022_remove_reaction_sequence_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeqPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_sequencing', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ext_standard_sequencing', models.DecimalField(decimal_places=2, max_digits=5)),
                ('well96_plate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ext_well96_plate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('large_template', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ext_large_template', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pcr_purification', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ext_pcr_purification', models.DecimalField(decimal_places=2, max_digits=5)),
                ('printout', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ext_printout', models.DecimalField(decimal_places=2, max_digits=5)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('current', models.BooleanField()),
            ],
        ),
    ]
