# Generated by Django 3.2.8 on 2021-11-08 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequences', '0023_seqprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seqprice',
            name='ext_large_template',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Large templates (external)'),
        ),
        migrations.AlterField(
            model_name='seqprice',
            name='ext_pcr_purification',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='PCR Purification (external)'),
        ),
        migrations.AlterField(
            model_name='seqprice',
            name='ext_printout',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Printout (external)'),
        ),
        migrations.AlterField(
            model_name='seqprice',
            name='ext_standard_sequencing',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Standard sequencing (external)'),
        ),
        migrations.AlterField(
            model_name='seqprice',
            name='ext_well96_plate',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='96-well plate (external)'),
        ),
        migrations.AlterField(
            model_name='seqprice',
            name='large_template',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Large templates (cosmid, etc)'),
        ),
        migrations.AlterField(
            model_name='seqprice',
            name='pcr_purification',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='PCR Purification'),
        ),
        migrations.AlterField(
            model_name='seqprice',
            name='standard_sequencing',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Standard Sequencing'),
        ),
        migrations.AlterField(
            model_name='seqprice',
            name='well96_plate',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='96-well plate (min 48)'),
        ),
    ]
