# Generated by Django 3.2.8 on 2021-11-10 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sequences', '0025_alter_reaction_submitter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='reaction',
            name='status',
            field=models.CharField(choices=[('s', 'Submitted'), ('p', 'Preparing'), ('r', 'Running'), ('d', 'Done'), ('q', 'Resequencing')], max_length=1),
        ),
        migrations.CreateModel(
            name='Worksheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.SmallIntegerField(default=1)),
                ('plate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sequences.plate')),
                ('reaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sequences.reaction')),
            ],
        ),
        migrations.AddField(
            model_name='plate',
            name='reactions',
            field=models.ManyToManyField(through='sequences.Worksheet', to='sequences.Reaction'),
        ),
    ]
