# Generated by Django 3.2.8 on 2021-11-10 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequences', '0026_auto_20211110_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksheet',
            name='well_count',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plate',
            name='reactions',
            field=models.ManyToManyField(related_name='plates', through='sequences.Worksheet', to='sequences.Reaction'),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='status',
            field=models.CharField(choices=[('s', 'Submitted'), ('p', 'Preparing'), ('r', 'Running'), ('d', 'Done'), ('v', 'Removed'), ('q', 'Resequencing')], max_length=1),
        ),
    ]
