# Generated by Django 3.2.8 on 2021-11-11 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequences', '0027_auto_20211110_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksheet',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
