# Generated by Django 3.2.8 on 2021-11-11 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sequences', '0029_auto_20211111_0816'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='worksheet',
            options={},
        ),
    ]
