# Generated by Django 3.2.8 on 2021-11-11 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sequences', '0030_alter_worksheet_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worksheet',
            old_name='version',
            new_name='block',
        ),
    ]
