# Generated by Django 3.2.8 on 2021-11-16 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequences', '0031_rename_version_worksheet_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plate',
            name='name',
            field=models.CharField(max_length=11),
        ),
    ]
