# Generated by Django 3.2.8 on 2021-11-16 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sequences', '0032_alter_plate_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reaction',
            name='plate_name',
        ),
        migrations.RemoveField(
            model_name='reaction',
            name='well',
        ),
    ]
