# Generated by Django 3.2.8 on 2021-11-18 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('headline', models.CharField(blank=True, max_length=150, null=True, verbose_name='Headline or Subject Line')),
                ('styling', models.CharField(blank=True, max_length=500, null=True, verbose_name='Inline CSS for styling (front page only)')),
                ('content', models.TextField(max_length=5000)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
