# Generated by Django 3.2.7 on 2021-09-29 14:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='comment',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
