# Generated by Django 3.2.7 on 2021-09-30 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20210929_1001'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['owner', '-is_active']},
        ),
        migrations.AlterField(
            model_name='preapproval',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approved_supervisor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='preapproval',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approved_student', to=settings.AUTH_USER_MODEL),
        ),
    ]
