# Generated by Django 3.2.7 on 2021-09-30 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20210930_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preapproval',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approved_student', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='preapproval',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approved_supervisor', to=settings.AUTH_USER_MODEL),
        ),
    ]
