# Generated by Django 3.2.7 on 2021-09-30 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20210930_0836'),
    ]

    operations = [
        migrations.AddField(
            model_name='preapproval',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_owner', to='accounts.account'),
        ),
    ]
