# Generated by Django 3.2.7 on 2021-09-30 12:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_preapproval_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='preapproval',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
