# Generated by Django 3.2.7 on 2021-10-04 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_preapproval_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preapproval',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_supervisors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='preapproval',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_students', to=settings.AUTH_USER_MODEL),
        ),
    ]
