# Generated by Django 3.2.8 on 2021-10-22 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20211004_0743'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='display_name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='LastName', max_length=150),
            preserve_default=False,
        ),
    ]
