# Generated by Django 3.2.8 on 2021-11-01 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20211022_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_student',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_supervisor',
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('p', 'Supervisor'), ('s', 'Student'), ('e', 'External')], default='s', max_length=1),
        ),
    ]
