# Generated by Django 3.2.8 on 2021-11-16 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20211101_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('p', 'Supervisor'), ('s', 'Student'), ('e', 'External')], default='s', max_length=1, verbose_name='User Type'),
        ),
    ]
